services:
  - type: web
    runtime: static
    name: alarma-nuclear-tiktok
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
